### ISSUE TITLE
Pinout incorrect, no instructions for flashing Klipper firmware

### ISSUE THREAD

**Issue by wandersoulz** [Mellow-3D/Fly-Gemini-V3#1]
The Gemini V3 board that I have does not have an SD card specific to the board itself. As such there is no way to flash the new klipper firmware and there are no instructions on how to do a command line based flashing.

**Comment by jaysuk** [comment]
sudo apt install libusb-1.0 pkg-config
cd ~/klipper/lib/hidflash
make
sudo ~/klipper/lib/hidflash/hid-flash ~/klipper/out/klipper.bin

**Comment by jaysuk** [comment]
Make the firmware the same as the Gemini v2

**Comment by wandersoulz** [comment]
These commands do not work for me. This is the output from running the `hid-flash` command:

```
+-----------------------------------------------------------------------+
|         HID-Flash v2.2.1 - STM32 HID Bootloader Flash Tool            |
|     (c)      2018 - Bruno Freitas       http://www.brunofreitas.com   |
|     (c) 2018-2019 - Vassilis Serasidis  https://www.serasidis.gr      |
|   Customized for STM32duino ecosystem   https://www.stm32duino.com    |
+-----------------------------------------------------------------------+

> Searching for [1209:BEBA] device...
##########
Error - [1209:BEBA] device is not found :(> Finish
```

**Comment by wandersoulz** [comment]
Are there board settings, jumper switch arrangements, or anything else that needs to be done before the flashing will work?

**Comment by jaysuk** [comment]
Nothing as far as I'm aware. I'll have to speak to flymaker tomorrow and
get back to you.
Those commands were given to me by him

**Comment by jaysuk** [comment]
please see the updated instructions here https://mellow.klipper.cn/#/board/fly_gemini_v3/flash

**Comment by roster210** [comment]
can you guys post the correct pinout? this does not have the endstop configuration the same also. what else is different?

**Comment by jaysuk** [comment]
removed the image so just the schematic available
