### ISSUE TITLE
V3 Pin Out - Heater Fan Voltage

### ISSUE THREAD

**Issue by wandersoulz** [Mellow-3D/Fly-Gemini-V3#2]
I added a new fan to my printer that is 5V but I believe that the board is providing 12v or 24v. Is there a jumper on the board to set the fan voltage?

**Comment by jaysuk** [comment]
there is a single fan voltage selector that sets the voltage for a fan0 and fan1. you can't set the voltages individually

**Comment by jaysuk** [comment]
removed the image
