### ISSUE TITLE
Pinout diagram Gemini_v3_pinout.svg inaccurate

### ISSUE THREAD

**Issue by eltoozero** [Mellow-3D/Fly-Gemini-V3#3]
Hardware pinout diagram in this repository is not accurate:

https://github.com/Mellow-3D/Fly-Gemini-V3/blob/main/Hardware/Gemini_v3_pinout.svg

![Gemini_v3_pinout](https://user-images.githubusercontent.com/14353674/229638302-0e48175a-56cd-4cb4-803c-abf81f6a0038.svg)

Documentation at https://mellow.klipper.cn/#/board/fly_gemini_v3/line

![endstop](https://user-images.githubusercontent.com/14353674/229638348-c6f83287-26b2-4a8e-8697-f2643906a1e2.png)

Shows the correct endstop pinouts for a v3.

Even the AliExpress listing for the v3 has incorrect picture for the board rear:
![Board Images (AliExpress)](https://user-images.githubusercontent.com/14353674/229638240-c201f62c-27c5-490b-ada6-a8fa244250d8.png)

**Comment by jaysuk** [comment]
best i can do with the info i have

**Comment by humbertocaron** [comment]
Thank goodness I read your post, I will hold on buying it then.
